import streamlit as st
import pandas as pd
import sys
import os

# Ensure src is in path so we can import ira
sys.path.append(os.path.abspath("src"))

from ira.ui.state import init_session_state
from ira.ui.profile_view import render_profile_view
from ira.ui.policy_editor import render_policy_editor
from ira.ui.correction_view import render_correction_view
from ira.ui.report_view import render_report_view

# Page Config
st.set_page_config(
    page_title="Insight Readiness Analyzer",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Initialize State
init_session_state()

# Header
st.title("🛡️ Insight Readiness Analyzer")
st.markdown("### A Data Quality Firewall for Modern Analytics")
st.markdown("---")

# Tabs for Workflow
tab_load, tab_profile, tab_policy, tab_correct, tab_report = st.tabs([
    "📂 Load Data", 
    "📊 Profiler", 
    "🔧 Policy", 
    "🧹 Correct", 
    "📥 Report"
])

# --- TAB 1: LOAD DATA ---
with tab_load:
    st.header("1. Upload Dataset")
    st.markdown("Start by uploading a messy CSV or Excel file.")
    
    # Option A: Dataset Upload
    uploaded_file = st.file_uploader(
        "📄 Upload Dataset (CSV/Excel)", 
        type=["csv", "xlsx", "xls"],
        help="Max size: 2.5GB. For larger files, use the CLI tool."
    )
    
    # Option B: Local File Path (Bypass Browser)
    local_path = st.text_input(
        "📂 OR Enter Local File Path (Bypass Browser Upload)", 
        help="Paste the absolute path to your file (e.g. /Users/name/data.csv). Best for large files."
    )
    
    # Option C: Profile JSON Upload (Offline Mode)
    uploaded_profile = st.file_uploader(
        "📊 OR Upload Profile JSON (Offline Mode)", 
        type=["json"],
        help="Upload a profile.json generated by `ira profile` CLI command."
    )

    # Context A/B: Raw Data (Upload or Local)
    source_file = uploaded_file or (local_path if local_path and os.path.exists(local_path) else None)
    
    if source_file:
        # Determine Name and Size
        if hasattr(source_file, "name"):
            # UploadedFile object
            fname = source_file.name
            fsize = source_file.size
        else:
            # Local Path string
            fname = os.path.basename(source_file)
            fsize = os.path.getsize(source_file)
            
        # Load Data
        if st.session_state.df is None or st.session_state.filename != fname:
            try:
                # Limit: 200MB for safe in-memory interactive editing
                LARGE_FILE_THRESHOLD = 200 * 1024 * 1024 
                
                if fsize > LARGE_FILE_THRESHOLD:
                    st.warning("⚠️ Large file detected (>200MB). Running in **Preview Mode** (First 10,000 rows only). For full processing, use the CLI.")
                    
                    if fname.lower().endswith(('.xlsx', '.xls')):
                         df = pd.read_excel(source_file, nrows=10000)
                    else:
                         # For local paths, we can read directly. For uploads, we seek.
                         if hasattr(source_file, "seek"):
                             source_file.seek(0)
                         df = pd.read_csv(source_file, nrows=10000)
                    
                    st.session_state.is_sample = True
                else:
                    if fname.lower().endswith(('.xlsx', '.xls')):
                        df = pd.read_excel(source_file)
                    else:
                        if hasattr(source_file, "seek"):
                            source_file.seek(0)
                        df = pd.read_csv(source_file)
                    st.session_state.is_sample = False
                
                st.session_state.df = df
                st.session_state.filename = fname
                
                # Store full path for large file local processing
                if local_path and os.path.exists(local_path):
                    st.session_state.source_path = local_path
                else:
                    st.session_state.source_path = None
                
                row_msg = f"{len(df)} rows" + (" (Sample)" if getattr(st.session_state, 'is_sample', False) else "")
                st.toast(f"Loaded {row_msg} from {fname}", icon="✅")
            except Exception as e:
                st.error(f"Error loading file: {e}")
    elif local_path and not os.path.exists(local_path):
        st.error(f"File not found: {local_path}")
    
    # Context C: Profile JSON
    if uploaded_profile is not None:
        import json
        try:
            profile_data = json.load(uploaded_profile)
            st.session_state.uploaded_profile = profile_data
            st.session_state.filename = uploaded_profile.name
            st.toast("Loaded Profile JSON successfully!", icon="📊")
        except Exception as e:
            st.error(f"Invalid JSON: {e}")

    # Display Status
    if st.session_state.df is not None:
        info_str = f"**File:** `{st.session_state.filename}` | **Rows:** {len(st.session_state.df)}"
        if getattr(st.session_state, 'is_sample', False):
            info_str += " (Preview Mode)"
        
        col_count = len(st.session_state.df.columns)
        st.info(f"{info_str} | **Cols:** {col_count} | **Simulated:** False")
        st.dataframe(st.session_state.df.head(10), use_container_width=True)
        st.success("👆 Data loaded! Go to the **Profiler** tab.")
        
    elif st.session_state.get("uploaded_profile"):
        meta = st.session_state.uploaded_profile.get("metadata", {})
        st.info(f"**Loaded Profile:** `{st.session_state.filename}` (Offline Mode)")
        st.write(f"**Original File:** {meta.get('dataset_name', 'Unknown')}")
        st.write(f"**Row Count:** {meta.get('row_count', 'Unknown')}")
        st.success("👆 Profile loaded! Go to the **Profiler** tab.")

# --- TAB 2: PROFILER ---
with tab_profile:
    render_profile_view()

with tab_policy:
    render_policy_editor()

with tab_correct:
    render_correction_view()

with tab_report:
    render_report_view()

# Sidebar Info
with st.sidebar:
    st.info("**IRA v1.0**\n\nEngine Status: 🟢 Strong\nUI Status: 🚧 Chunk 5 (Report)")
    if st.button("Reset App"):
        st.session_state.clear()
        st.rerun()
