from typing import Any, Dict, List, Optional
import streamlit as st
import pandas as pd
import json
import io

def render_report_view():
    st.subheader("📊 Final Report & Download")
    
    # Check for In-Memory Result
    has_memory_data = "cleaned_df" in st.session_state and st.session_state.cleaned_df is not None
    
    report_data = None
    
    if has_memory_data:
        original_df = st.session_state.df
        cleaned_df = st.session_state.cleaned_df
        audit_stats = st.session_state.get("audit_stats", pd.DataFrame())
        
        # Calculate metrics for dynamic display
        rows_orig = len(original_df)
        rows_clean = len(cleaned_df)
        cols_orig = len(original_df.columns)
        cols_clean = len(cleaned_df.columns)
        total_mods = audit_stats["Count"].sum() if not audit_stats.empty else 0
        
        # Missing values (expensive on large df, but this is memory mode so ok)
        missing_orig = original_df.isnull().sum().sum()
        missing_clean = cleaned_df.isnull().sum().sum()
        
    else:
        # Offline Mode Uploader
        st.info("⚠️ No active correction run found in memory.")
        uploaded_report = st.file_uploader("📂 Upload `report.json` (from CLI run) to view results", type=["json"])
        
        if uploaded_report is not None:
             try:
                 report_data = json.load(uploaded_report)
                 st.success("Report loaded successfully!")
                 
                 # Extract metrics from JSON
                 meta = report_data.get("metadata", {})
                 readiness = report_data.get("readiness", {})
                 actions = report_data.get("actions", {})
                 
                 rows_orig = meta.get("rows_raw", 0)
                 rows_clean = meta.get("rows_optimized", 0)
                 # JSON doesn't track col count delta explicitly usually, but Profile does
                 # We'll just skip col delta if not present
                 cols_orig = 0 
                 cols_clean = 0
                 
                 total_mods = sum(actions.get("event_counts", {}).values())
                 
                 # JSON report doesn't usually store raw missing count, only percentages in profile
                 # We will omit Missing Value Delta for offline mode or infer?
                 missing_orig = None
                 missing_clean = None
                 
             except Exception as e:
                 st.error(f"Invalid JSON: {e}")
                 return
        else:
            return  # Nothing to show

    # --- Comparison Metrics ---
    st.subheader("Comparison Summary")
    
    col1, col2, col3, col4 = st.columns(4)
    
    # Rows
    rows_delta = rows_clean - rows_orig
    col1.metric("Total Rows", rows_clean, delta=f"{rows_delta}" if rows_delta != 0 else "No Change")
    
    # Columns
    if has_memory_data:
        col2.metric("Columns", cols_clean, delta=f"{cols_clean - cols_orig}" if cols_clean != cols_orig else "No Change")
    else:
        col2.metric("Columns", "N/A (Offline)")

    # Missing Values
    if missing_orig is not None:
        missing_delta = missing_clean - missing_orig
        col3.metric("Total Missing Values", missing_clean, delta=f"{missing_delta}" if missing_delta != 0 else "No Change", delta_color="inverse")
    else:
        col3.metric("Total Missing Values", "N/A (Offline)")
    
    # Modifications
    col4.metric("Total Modifications", total_mods, delta="Applied" if total_mods > 0 else None)
    
    st.divider()
    
    # --- Download Section ---
    st.subheader("💾 Download Results")
    
    if has_memory_data:
        col_d1, col_d2, col_d3 = st.columns(3)
        
        # 1. Cleaned Data (CSV)
        csv_buffer = io.StringIO()
        cleaned_df.to_csv(csv_buffer, index=False)
        csv_data = csv_buffer.getvalue()
        
        col_d1.download_button(
            label="Download Clean Data (CSV)",
            data=csv_data,
            file_name="cleaned_data.csv",
            mime="text/csv",
            type="primary"
        )
        
        # 2. Audit Log (JSON)
        if "audit_samples" in st.session_state:
            audit_data = st.session_state.audit_samples
            json_data = json.dumps(audit_data, indent=2, default=str)
            col_d2.download_button(
                label="Download Audit Log (JSON)",
                data=json_data,
                file_name="audit_log.json",
                mime="application/json"
            )
            
    else:
        st.info("ℹ️ Data CSV and Audit Log are available on your disk (generated by CLI).")

    # 3. Summary Report (Markdown)
    # If in memory, generate it. If offline, regenerate from loaded JSON.
    from ira.reporting.report import generate_markdown_report
    
    if has_memory_data:
        # We need the full report object from memory run? 
        # Actually report_view previously manually built md string.
        # Ideally we should assume the backend produced a 'report_obj' in session
        # But looking at previous code, it generated MD string on the fly from partial stats.
        # Let's stick to the previous simple MD generation for memory, or try to enable the robust one?
        # Robust one requires 'report' dict.
        pass # use legacy generation below or... 
        # Actually, let's keep the legacy inline generation for memory mode to avoid breaking changes
        # AND add the robust generation for offline mode.
        
    if not has_memory_data and report_data:
         # Offline Mode: Generate MD from JSON
         from ira.reporting.report import generate_markdown_report
         report_md = generate_markdown_report(report_data)
         st.download_button(
            label="Download Report (Text/Markdown)",
            data=report_md,
            file_name="readiness_report.txt",
            mime="text/plain"
        )
    elif has_memory_data:
        # In-Memory Mode (Legacy MD generation)
        report_md = f"""# Data Readiness Report
Generated by Insight Readiness Analyzer (IRA)

## Summary
- **Original Rows:** {rows_orig}
- **Clean Rows:** {rows_clean}
- **Total Modifications:** {total_mods}

## Audit Summary
"""
        if not audit_stats.empty:
            report_md += audit_stats.to_markdown(index=False)
        else:
            report_md += "No modifications were performed."
            
        col_dest = col_d3 if has_memory_data else st 
        col_dest.download_button(
            label="Download Report (Text/Markdown)",
            data=report_md,
            file_name="readiness_report.txt",
            mime="text/plain"
        )

    # --- Analysis Preview ---
    if has_memory_data:
        with st.expander("View Clean Data Preview", expanded=True):
            st.dataframe(cleaned_df.head(100))
